# name: eertseBuild, Publish and Deploy to Kubernetes

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# env:
#   REGISTRY: registry.digitalocean.com
#   IMAGE_NAME: registry.digitalocean.com/rustxregistry/rustx-container

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#       id-token: write

#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log into DigitalOcean Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and Push Docker Image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: |
#             ${{ env.IMAGE_NAME }}:latest

#       - name: Create .kube directory
#         run: mkdir -p $HOME/.kube

#       - name: Set KUBECONFIG
#         run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

#       - name: Install kubectl
#         run: |
#           curl -LO "https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl"
#           chmod +x ./kubectl
#           sudo mv ./kubectl /usr/local/bin/kubectl

#       - name: Apply Kubernetes Deployment
#         run: |
#           kubectl apply -f rust_deployment.yaml
